name: Building and Pushing Python Image to Google Cloud Platform
on:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }} 
      APPLICATION_NAME: myapp
      REGION: us-east1
      PROJECT_NUMBER: ${{secrets.PROJECT_NUMBER}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }} 
        export_default_credentials: true
    - name: Build
      run: |-
        gcloud builds submit --quiet  --tag "gcr.io/$PROJECT_ID/$APPLICATION_NAME:$GITHUB_SHA"

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy $APPLICATION_NAME \
          --quiet \
          --region "$REGION" \
          --image "gcr.io/$PROJECT_ID/$APPLICATION_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated